---
- name: install PostreSQL
  yum:
    name: postgresql-server
    state: latest

- name: initilize postgres
  command: postgresql-setup initdb
  args:
      creates: /var/lib/pgsql/data/pg_clog

- name: enable PostgreSQL on boot
  service:
    name: postgresql
    state: started
    enabled: yes

