---

- name: Provision 3 tier application
  hosts: all
  become: true
  gather_facts: true
  tasks:

  - name: Configuration
    include_role:
      name: configuration

  - name: Configure Application DBs
    include_role:
      name: dbs  
    when: >-
      'appdbs' in group_names

  - name: Application Servers
    become: true
    block:
      - name: Tomcat
        include_role:
          name: tomcat
      - name: Apps
        include_role:
          name: apps
    when: >-
      'apps' in group_names
   
  - name: Front End Servers
    include_role:
      name: haproxy
    when: >-
      'frontends' in group_names
