---
- name: Install Tomcat
  yum:
    name: tomcat
    state: present
- name: Enable Tomcat at boot
  service:
      name: tomcat
      enabled: yes
  notify: 
    - restart tomcat
- name: create ansible tomcat directory
  file:
      path: /usr/share/tomcat/webapps/ansible
      state: directory
  notify: 
    - restart tomcat

- name: Install application for host {{ ansible_hostname }}
  template:
    src: index.html.{{ ansible_hostname }}
    dest: /usr/share/tomcat/webapps/ansible/index.html
    mode: 0644
  notify: 
    - restart tomcat
